name: shoes_shop
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a `+`.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets section
  assets:
    - assets/images/bhuwan.jpeg
    - assets/images/sishu.jpg
    - assets/images/latte.png

  # Fonts section
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans_Condensed-SemiBold.ttf
          weight: 700
    - family: Cera
      fonts:
        - asset: assets/fonts/ceraroundpro-regular.otf
          weight: 400